
[profile.bench]
debug = true

[profile.release]
#lto = true
debug = true

[workspace]
members = [
	"cloudflow",
    "memflow-node",
	"filer",
	"filer-fuse",
	"cloudflow-minidump"
]
default-members = [
	"cloudflow",
    "memflow-node",
	"filer",
	"filer-fuse",
	"cloudflow-minidump"
]
